
# 🧠 **Understanding Embeddings with BERT**

In this notebook, we go into the world of embeddings, utilizing the BERT model to understand the semantic relationships between words in different contexts.

## 🛠️ Setup and Installation

Start by installing the necessary libraries to ensure all functionalities are available.

In [2]:
#!pip install transformers==4.29.2
#!pip install scipy==1.7.3
!pip install scipy


[notice] A new release of pip is available: 25.0 -> 25.3
[notice] To update, run: C:\Users\meisa\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


## 📚 Importing Libraries

Import essential modules for our tasks.

In [1]:
from transformers import BertModel, AutoTokenizer
#from scipy.spatial.distance import cosine

## 🤖 Model Setup

Load the pre-trained BERT model and tokenizer. This model will help us extract embeddings for our analysis.

In [2]:
# Defining the model name
model_name = "bert-base-cased"

# Loading the pre-trained model and tokenizer
model = BertModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [3]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(28996, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False


## 📝 Function Definition: Predict

Define a function that encodes input text into tensors, which are then fed to the model to obtain embeddings.

In [ ]:
# Defining a function to encode the input text and get model predictions
def predict(text):
    encoded_inputs = tokenizer(text, return_tensors="pt")
    return model(**encoded_inputs)[0]       # vector in last_hidden_state

## 📃 Defining the Sentences

Set up sentences to analyze. The

In [19]:
# Defining the sentences
sentence1 = "There was a fly drinking from my soup"
#sentence2 = "There is a fly swimming in my juice"
sentence2 = "To become a commercial pilot, he had to fly for 1500 hours and eat soup." 

# Tokenizing the sentences
tokens1 = tokenizer.tokenize(sentence1)     
encoder1 = tokenizer.encode(sentence1)
tokens2 = tokenizer.tokenize(sentence2)

print(tokens1)
print(encoder1)
print(tokenizer.convert_ids_to_tokens(encoder1))
print(tokens1.index("fly"))
print(tokens2.index("fly"))

['There', 'was', 'a', 'fly', 'drinking', 'from', 'my', 'soup']
[101, 1247, 1108, 170, 4689, 5464, 1121, 1139, 13128, 102]
['[CLS]', 'There', 'was', 'a', 'fly', 'drinking', 'from', 'my', 'soup', '[SEP]']
3
9


## 🔍 Tokenization and Model Predictions

Tokenize the sentences and obtain predictions (embeddings) from the model.

In [20]:
# Getting model predictions for the sentences
out1 = predict(sentence1)
out2 = predict(sentence2)

print(out1.shape)       # (batch_size, sequence_length, hidden_size)
print(out2.shape)

torch.Size([1, 10, 768])
torch.Size([1, 19, 768])


## 🔄 Extracting Embeddings

Extract embeddings specifically for the word "fly" from both sentences.

In [21]:
# Extracting embeddings for the word 'fly' in both sentences
emb1 = out1[0:, tokens1.index("fly"), :].detach()[0]
emb2 = out2[0:, tokens2.index("fly"), :].detach()[0]

print(emb1[:10])
print(emb2[:10])

# emb1 = out1[0:, 3, :].detach()
# emb2 = out2[0:, 3, :].detach()

tensor([ 0.1309, -0.1067,  0.0925,  0.1364, -0.0204, -0.4588,  0.2813,  0.0616,
        -0.3543, -0.2147])
tensor([ 0.2645, -0.5573,  0.0890, -0.2589,  0.3056, -0.0167,  0.2368,  0.1930,
         0.1306,  0.0937])


In [24]:
emb1 = out1[0:, tokens1.index("soup")+1, :].detach()[0]
emb2 = out2[0:, tokens2.index("soup")+1, :].detach()[0]

print(emb1[:10])
print(emb2[:10])

tensor([ 2.3282e-01,  1.3083e-02,  2.1305e-01, -6.7307e-02,  2.8090e-02,
        -4.2697e-01, -1.6177e-01,  4.2518e-02,  2.2084e-04, -3.7039e-01])
tensor([ 0.1625, -0.0159, -0.0040,  0.0762, -0.1015,  0.2041, -0.0172,  0.2607,
        -0.2903, -0.0352])


## 📊 Calculating Cosine Similarity

Calculate the cosine similarity between the embeddings of the word "fly" from both sentences to measure how context affects meaning.

In [25]:
# Calculating the cosine similarity between the embeddings
#cosine(emb1, emb2)

import numpy as np

def cosine_sim(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosine_sim(emb1.numpy(), emb2.numpy())

np.float32(0.65959495)

## 🌟 Conclusion

This notebook has guided you through the process of extracting and comparing word embeddings using BERT. Such techniques are fundamental in understanding word semantics and their usage across different contexts.

Experiment by changing the sentences or focusing on different words to see how the embeddings and their similarities vary!